import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pegawai',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar bg-blue-600 text-neutral-content">
          <a className="btn btn-ghost normal-case text-xl">Pegawai</a>
        </div>
        <div className="px-5 py-5">{children}</div>
      </body>
    </html>
  )
}
